/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package onlinesubscriptionservice;

import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 * Jack Martin
 * 15009787
 */

public class RunGUI extends javax.swing.JFrame {

    /**
     * Creates new form frame
     */
    
    public RunGUI() {
        initComponents();
        setup();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestBookingPanel = new javax.swing.JTabbedPane();
        addNewMemberPanel = new javax.swing.JPanel();
        newMemberIDNumberLabel = new javax.swing.JLabel();
        newMemberNameLabel = new javax.swing.JLabel();
        newMemberNameTextField = new javax.swing.JTextField();
        newMemberIDNumberTextField = new javax.swing.JTextField();
        addMemberButton = new javax.swing.JButton();
        useTextFileMemberButton = new javax.swing.JButton();
        searchItemPanel = new javax.swing.JPanel();
        enterSearchTermLabel = new javax.swing.JLabel();
        searchTermTextField = new javax.swing.JTextField();
        searchItemsButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchResultsTextBox = new javax.swing.JTextArea();
        viewCurrentBookingsPanel = new javax.swing.JPanel();
        memberIDNumberLabel = new javax.swing.JLabel();
        memberIDNumberTextField = new javax.swing.JTextField();
        viewCurrentBookingsButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        currentBookingsTextBox = new javax.swing.JTextArea();
        memberIDLabel = new javax.swing.JLabel();
        addNewItemPanel = new javax.swing.JPanel();
        newItemIDNumberLabel = new javax.swing.JLabel();
        newItemNameLabel = new javax.swing.JLabel();
        newItemIDNumberTextField = new javax.swing.JTextField();
        newItemNameTextField = new javax.swing.JTextField();
        addItemButton = new javax.swing.JButton();
        newItemNumberAvailableLabel = new javax.swing.JLabel();
        newItemNumberAvailableTextField = new javax.swing.JTextField();
        useTextFileItemButton = new javax.swing.JButton();
        requetBookingPanel = new javax.swing.JPanel();
        bookItemIDNumberLabel = new javax.swing.JLabel();
        bookItemIDNumberTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        bookItemPreviewTextBox = new javax.swing.JTextArea();
        findItemButton = new javax.swing.JToggleButton();
        requestBookingButton = new javax.swing.JToggleButton();
        requestBookingLabel = new javax.swing.JLabel();
        bookItemMemberIDTextField = new javax.swing.JTextField();
        transactionIDLabel = new javax.swing.JLabel();
        bookItemTransactionIDTextField = new javax.swing.JTextField();
        transactionDateLabel = new javax.swing.JLabel();
        bookItemTransactionDateTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frame"); // NOI18N

        requestBookingPanel.setToolTipText("");
        requestBookingPanel.setName("Add New User"); // NOI18N

        newMemberIDNumberLabel.setText("Enter Member ID Number");

        newMemberNameLabel.setText("Enter Member Name");

        newMemberNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMemberNameTextFieldActionPerformed(evt);
            }
        });

        newMemberIDNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMemberIDNumberTextFieldActionPerformed(evt);
            }
        });

        addMemberButton.setText("Add Member ");
        addMemberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMemberButtonActionPerformed(evt);
            }
        });

        useTextFileMemberButton.setText("Use Text File");
        useTextFileMemberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useTextFileMemberButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addNewMemberPanelLayout = new javax.swing.GroupLayout(addNewMemberPanel);
        addNewMemberPanel.setLayout(addNewMemberPanelLayout);
        addNewMemberPanelLayout.setHorizontalGroup(
            addNewMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addNewMemberPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addMemberButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(addNewMemberPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(addNewMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addNewMemberPanelLayout.createSequentialGroup()
                        .addComponent(useTextFileMemberButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(addNewMemberPanelLayout.createSequentialGroup()
                        .addGroup(addNewMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newMemberNameLabel)
                            .addComponent(newMemberIDNumberLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(addNewMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newMemberNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newMemberIDNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51))))
        );
        addNewMemberPanelLayout.setVerticalGroup(
            addNewMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewMemberPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(addNewMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newMemberIDNumberLabel)
                    .addComponent(newMemberIDNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(addNewMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newMemberNameLabel)
                    .addComponent(newMemberNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(useTextFileMemberButton)
                .addGap(36, 36, 36)
                .addComponent(addMemberButton)
                .addGap(34, 34, 34))
        );

        requestBookingPanel.addTab("Add New User", addNewMemberPanel);

        enterSearchTermLabel.setText("Enter Item Name");

        searchTermTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTermTextFieldActionPerformed(evt);
            }
        });

        searchItemsButton.setText("Search Items");
        searchItemsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchItemsButtonActionPerformed(evt);
            }
        });

        searchResultsTextBox.setColumns(20);
        searchResultsTextBox.setRows(5);
        jScrollPane1.setViewportView(searchResultsTextBox);

        javax.swing.GroupLayout searchItemPanelLayout = new javax.swing.GroupLayout(searchItemPanel);
        searchItemPanel.setLayout(searchItemPanelLayout);
        searchItemPanelLayout.setHorizontalGroup(
            searchItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchItemPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(searchItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(enterSearchTermLabel)
                    .addGroup(searchItemPanelLayout.createSequentialGroup()
                        .addComponent(searchTermTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchItemsButton)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        searchItemPanelLayout.setVerticalGroup(
            searchItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchItemPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(enterSearchTermLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTermTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchItemsButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        requestBookingPanel.addTab("Search Item", searchItemPanel);

        memberIDNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberIDNumberTextFieldActionPerformed(evt);
            }
        });

        viewCurrentBookingsButton.setText("View Current Bookings");
        viewCurrentBookingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCurrentBookingsButtonActionPerformed(evt);
            }
        });

        currentBookingsTextBox.setColumns(20);
        currentBookingsTextBox.setRows(5);
        jScrollPane3.setViewportView(currentBookingsTextBox);

        memberIDLabel.setText("Enter MemberID Number");
        memberIDLabel.setToolTipText("");

        javax.swing.GroupLayout viewCurrentBookingsPanelLayout = new javax.swing.GroupLayout(viewCurrentBookingsPanel);
        viewCurrentBookingsPanel.setLayout(viewCurrentBookingsPanelLayout);
        viewCurrentBookingsPanelLayout.setHorizontalGroup(
            viewCurrentBookingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewCurrentBookingsPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(viewCurrentBookingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(viewCurrentBookingsButton)
                    .addGroup(viewCurrentBookingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(viewCurrentBookingsPanelLayout.createSequentialGroup()
                            .addComponent(memberIDNumberLabel)
                            .addGap(18, 18, 18)
                            .addComponent(memberIDLabel)
                            .addGap(18, 18, 18)
                            .addComponent(memberIDNumberTextField))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        viewCurrentBookingsPanelLayout.setVerticalGroup(
            viewCurrentBookingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewCurrentBookingsPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(viewCurrentBookingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(memberIDNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(viewCurrentBookingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(memberIDNumberLabel)
                        .addComponent(memberIDLabel)))
                .addGap(27, 27, 27)
                .addComponent(viewCurrentBookingsButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        requestBookingPanel.addTab("View Current Bookings", viewCurrentBookingsPanel);

        newItemIDNumberLabel.setText("Enter Item ID Number");

        newItemNameLabel.setText("Enter Item Name");

        newItemIDNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newItemIDNumberTextFieldActionPerformed(evt);
            }
        });

        newItemNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newItemNameTextFieldActionPerformed(evt);
            }
        });

        addItemButton.setText("Add Item");
        addItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemButtonActionPerformed(evt);
            }
        });

        newItemNumberAvailableLabel.setText("Enter Number Available");

        newItemNumberAvailableTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newItemNumberAvailableTextFieldActionPerformed(evt);
            }
        });

        useTextFileItemButton.setText("Use Text File");
        useTextFileItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useTextFileItemButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addNewItemPanelLayout = new javax.swing.GroupLayout(addNewItemPanel);
        addNewItemPanel.setLayout(addNewItemPanelLayout);
        addNewItemPanelLayout.setHorizontalGroup(
            addNewItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewItemPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(addNewItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addNewItemPanelLayout.createSequentialGroup()
                        .addComponent(newItemIDNumberLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(newItemIDNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addNewItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(useTextFileItemButton)
                        .addGroup(addNewItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(addNewItemPanelLayout.createSequentialGroup()
                                .addComponent(newItemNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(newItemNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addNewItemPanelLayout.createSequentialGroup()
                                .addComponent(newItemNumberAvailableLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(newItemNumberAvailableTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addNewItemPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        addNewItemPanelLayout.setVerticalGroup(
            addNewItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addNewItemPanelLayout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(addNewItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newItemIDNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newItemIDNumberLabel))
                .addGap(34, 34, 34)
                .addGroup(addNewItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newItemNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newItemNameLabel))
                .addGap(32, 32, 32)
                .addGroup(addNewItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newItemNumberAvailableLabel)
                    .addComponent(newItemNumberAvailableTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(useTextFileItemButton)
                .addGap(8, 8, 8)
                .addComponent(addItemButton)
                .addGap(36, 36, 36))
        );

        requestBookingPanel.addTab("Add New Item", addNewItemPanel);

        bookItemIDNumberLabel.setText("Enter Item ID Number");

        bookItemPreviewTextBox.setColumns(20);
        bookItemPreviewTextBox.setRows(5);
        jScrollPane2.setViewportView(bookItemPreviewTextBox);

        findItemButton.setText("Find Item");
        findItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findItemButtonActionPerformed(evt);
            }
        });

        requestBookingButton.setText("Request Booking");
        requestBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestBookingButtonActionPerformed(evt);
            }
        });

        requestBookingLabel.setText("Enter Member ID Number");

        bookItemMemberIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookItemMemberIDTextFieldActionPerformed(evt);
            }
        });

        transactionIDLabel.setText("Enter Transaction ID Number");

        transactionDateLabel.setText("Enter Transaction Date");

        javax.swing.GroupLayout requetBookingPanelLayout = new javax.swing.GroupLayout(requetBookingPanel);
        requetBookingPanel.setLayout(requetBookingPanelLayout);
        requetBookingPanelLayout.setHorizontalGroup(
            requetBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(requetBookingPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(requetBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(requetBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(requetBookingPanelLayout.createSequentialGroup()
                            .addComponent(requestBookingLabel)
                            .addGap(18, 18, 18)
                            .addComponent(bookItemMemberIDTextField)
                            .addGap(18, 18, 18)
                            .addComponent(requestBookingButton))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, requetBookingPanelLayout.createSequentialGroup()
                            .addComponent(bookItemIDNumberLabel)
                            .addGap(18, 18, 18)
                            .addComponent(bookItemIDNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(findItemButton)))
                    .addGroup(requetBookingPanelLayout.createSequentialGroup()
                        .addGroup(requetBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(transactionIDLabel)
                            .addComponent(transactionDateLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(requetBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bookItemTransactionDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bookItemTransactionIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        requetBookingPanelLayout.setVerticalGroup(
            requetBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(requetBookingPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(requetBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookItemIDNumberLabel)
                    .addComponent(bookItemIDNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findItemButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(requetBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transactionIDLabel)
                    .addComponent(bookItemTransactionIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(requetBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transactionDateLabel)
                    .addComponent(bookItemTransactionDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(requetBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(requestBookingButton)
                    .addComponent(requestBookingLabel)
                    .addComponent(bookItemMemberIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        requestBookingPanel.addTab("Request Booking", requetBookingPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(requestBookingPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(requestBookingPanel)
        );

        requestBookingPanel.getAccessibleContext().setAccessibleName("Add New User");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newMemberIDNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMemberIDNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newMemberIDNumberTextFieldActionPerformed

    private void newMemberNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMemberNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newMemberNameTextFieldActionPerformed

    private void searchTermTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTermTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTermTextFieldActionPerformed

    private void memberIDNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberIDNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memberIDNumberTextFieldActionPerformed

    private void viewCurrentBookingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCurrentBookingsButtonActionPerformed
        // TODO add your handling code here:
        String memberIDNumber = memberIDNumberTextField.getText();
        String error = sysMan.validateMemberIDNumber(memberIDNumber);
        if (error != null) {
            JOptionPane.showMessageDialog(viewCurrentBookingsPanel, error, "Error", JOptionPane.ERROR_MESSAGE);
        }
        else {
            String results = sysMan.viewCurrentBookings(memberIDNumber);
            if (results != null) {
                currentBookingsTextBox.setText(results);
            }
        }
        
    }//GEN-LAST:event_viewCurrentBookingsButtonActionPerformed

    private void useTextFileMemberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useTextFileMemberButtonActionPerformed
        // TODO add your handling code here:
        String error = sysMan.addMemberTextFile();
        if (error != null) {
            JOptionPane.showMessageDialog(addNewMemberPanel, error, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_useTextFileMemberButtonActionPerformed

    private void addMemberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMemberButtonActionPerformed
        String newMemberIDNumber = newMemberIDNumberTextField.getText();
        String newMemberName = newMemberNameTextField.getText();
        
        newMemberIDNumberTextField.setText("");
        newMemberNameTextField.setText("");
        
        String error = sysMan.addMember(newMemberIDNumber, newMemberName);
        
        if (error != null) {
            JOptionPane.showMessageDialog(addNewMemberPanel, error, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addMemberButtonActionPerformed

    private void newItemIDNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newItemIDNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newItemIDNumberTextFieldActionPerformed

    private void newItemNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newItemNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newItemNameTextFieldActionPerformed

    private void addItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemButtonActionPerformed
        // TODO add your handling code here:
        String newItemIDNumber = newItemIDNumberTextField.getText();
        String newItemName = newItemNameTextField.getText();
        String newItemInitialNumberAvailable = newItemNumberAvailableTextField.getText();
        newItemIDNumberTextField.setText("");
        newItemNameTextField.setText("");
        newItemNumberAvailableTextField.setText("");
        
        String error = sysMan.addItem(newItemIDNumber, newItemName, newItemInitialNumberAvailable);
        
        if (error != null) {
            JOptionPane.showMessageDialog(addNewItemPanel, error, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addItemButtonActionPerformed

    private void newItemNumberAvailableTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newItemNumberAvailableTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newItemNumberAvailableTextFieldActionPerformed

    private void searchItemsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchItemsButtonActionPerformed
        // TODO add your handling code here:
        searchResultsTextBox.setText("");
        String searchTerm = searchTermTextField.getText();
        String results = sysMan.searchItems(searchTerm);
        searchResultsTextBox.setText(results);
        if ("".equals(searchResultsTextBox.getText())) {
            JOptionPane.showMessageDialog(searchItemPanel, "No items found", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_searchItemsButtonActionPerformed

    private void findItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findItemButtonActionPerformed
        // TODO add your handling code here:
        String searchID = bookItemIDNumberTextField.getText();
        bookItemPreviewTextBox.setText("");
        String error = sysMan.validateFindItemSearchTerm(searchID);
        if (error != null) {
            JOptionPane.showMessageDialog(requestBookingPanel, error, "Error", JOptionPane.ERROR_MESSAGE);
        }
        else {
            String locatedItem = sysMan.findItem(searchID);
            if (locatedItem == null) {
               JOptionPane.showMessageDialog(requestBookingPanel, "No items found", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
            else {
               bookItemPreviewTextBox.setText(locatedItem);
            }
        }
    }//GEN-LAST:event_findItemButtonActionPerformed

    private void requestBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestBookingButtonActionPerformed
        // TODO add your handling code here:
        String transactionIDNumber = bookItemTransactionIDTextField.getText();
        String transactionDate = bookItemTransactionDateTextField.getText();
        String memberIDNumber = bookItemMemberIDTextField.getText();
        String message = sysMan.requestBooking(transactionIDNumber, memberIDNumber, transactionDate);
        if (message != null) {
            JOptionPane.showMessageDialog(requestBookingPanel, message, "Information", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_requestBookingButtonActionPerformed

    private void useTextFileItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useTextFileItemButtonActionPerformed
        // TODO add your handling code here:
        String error = sysMan.addItemTextFile();
        if (error != null) {
            JOptionPane.showMessageDialog(addNewMemberPanel, error, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_useTextFileItemButtonActionPerformed

    private void bookItemMemberIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookItemMemberIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookItemMemberIDTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RunGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RunGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RunGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RunGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RunGUI().setVisible(true);
            }
        });
    }
    
    private void setup() {
        sysMan = new SystemManager();
    }
    
    private SystemManager sysMan;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addItemButton;
    private javax.swing.JButton addMemberButton;
    private javax.swing.JPanel addNewItemPanel;
    private javax.swing.JPanel addNewMemberPanel;
    private javax.swing.JLabel bookItemIDNumberLabel;
    private javax.swing.JTextField bookItemIDNumberTextField;
    private javax.swing.JTextField bookItemMemberIDTextField;
    private javax.swing.JTextArea bookItemPreviewTextBox;
    private javax.swing.JTextField bookItemTransactionDateTextField;
    private javax.swing.JTextField bookItemTransactionIDTextField;
    private javax.swing.JTextArea currentBookingsTextBox;
    private javax.swing.JLabel enterSearchTermLabel;
    private javax.swing.JToggleButton findItemButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel memberIDLabel;
    private javax.swing.JLabel memberIDNumberLabel;
    private javax.swing.JTextField memberIDNumberTextField;
    private javax.swing.JLabel newItemIDNumberLabel;
    private javax.swing.JTextField newItemIDNumberTextField;
    private javax.swing.JLabel newItemNameLabel;
    private javax.swing.JTextField newItemNameTextField;
    private javax.swing.JLabel newItemNumberAvailableLabel;
    private javax.swing.JTextField newItemNumberAvailableTextField;
    private javax.swing.JLabel newMemberIDNumberLabel;
    private javax.swing.JTextField newMemberIDNumberTextField;
    private javax.swing.JLabel newMemberNameLabel;
    private javax.swing.JTextField newMemberNameTextField;
    private javax.swing.JToggleButton requestBookingButton;
    private javax.swing.JLabel requestBookingLabel;
    private javax.swing.JTabbedPane requestBookingPanel;
    private javax.swing.JPanel requetBookingPanel;
    private javax.swing.JPanel searchItemPanel;
    private javax.swing.JButton searchItemsButton;
    private javax.swing.JTextArea searchResultsTextBox;
    private javax.swing.JTextField searchTermTextField;
    private javax.swing.JLabel transactionDateLabel;
    private javax.swing.JLabel transactionIDLabel;
    private javax.swing.JButton useTextFileItemButton;
    private javax.swing.JButton useTextFileMemberButton;
    private javax.swing.JButton viewCurrentBookingsButton;
    private javax.swing.JPanel viewCurrentBookingsPanel;
    // End of variables declaration//GEN-END:variables

}
