/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package isbncreditcardverification;

/**
 *
 * @author Jack Martin (15009787)
 * 
 */
public class RunGUI extends javax.swing.JFrame {

    /**
     * Creates new form RunGUI
     */
    public RunGUI() {
        initComponents();
        setup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        isbnInputField = new javax.swing.JTextField();
        verifyISBNButton = new javax.swing.JButton();
        creditCardNoInputField = new javax.swing.JTextField();
        creditCardNoInputLabel = new javax.swing.JLabel();
        isbnInputLabel = new javax.swing.JLabel();
        verifyCreditCardNoButton = new javax.swing.JButton();
        outputScrollPane = new javax.swing.JScrollPane();
        outputField = new javax.swing.JTextArea();
        modCalcBtn = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        footnoteLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        isbnInputField.setText(" ");
        isbnInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isbnInputFieldActionPerformed(evt);
            }
        });

        verifyISBNButton.setText("Verify ISBN");
        verifyISBNButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyISBNButtonActionPerformed(evt);
            }
        });

        creditCardNoInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditCardNoInputFieldActionPerformed(evt);
            }
        });

        creditCardNoInputLabel.setText("Enter Credit Card Number");

        isbnInputLabel.setText("Enter ISBN");

        verifyCreditCardNoButton.setText("Verify Credit Card Number");
        verifyCreditCardNoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyCreditCardNoButtonActionPerformed(evt);
            }
        });

        outputField.setColumns(20);
        outputField.setRows(5);
        outputScrollPane.setViewportView(outputField);

        modCalcBtn.setText("Mod Calculator");
        modCalcBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modCalcBtnActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        footnoteLabel.setText("Please note that any non-numeric characters will be ignored");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(footnoteLabel)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(verifyCreditCardNoButton)
                    .addComponent(verifyISBNButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(modCalcBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clearButton))
                        .addComponent(creditCardNoInputLabel)
                        .addComponent(isbnInputLabel)
                        .addComponent(outputScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addComponent(creditCardNoInputField)
                        .addComponent(isbnInputField)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(isbnInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(isbnInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(verifyISBNButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(creditCardNoInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(creditCardNoInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(verifyCreditCardNoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modCalcBtn)
                    .addComponent(clearButton))
                .addGap(18, 18, 18)
                .addComponent(footnoteLabel)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void isbnInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isbnInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isbnInputFieldActionPerformed

    private void verifyISBNButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyISBNButtonActionPerformed
        // TODO add your handling code here:
        String isbnNumber = isbnInputField.getText();
        String output = isbnVerification.verifyInput(isbnNumber);
        outputField.setText(output);
    }//GEN-LAST:event_verifyISBNButtonActionPerformed

    private void creditCardNoInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditCardNoInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditCardNoInputFieldActionPerformed

    private void verifyCreditCardNoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyCreditCardNoButtonActionPerformed
        // TODO add your handling code here:
        String creditCardNo = creditCardNoInputField.getText();
        String output = creditCardNoVerification.verifyInput(creditCardNo);
        outputField.setText(output);
    }//GEN-LAST:event_verifyCreditCardNoButtonActionPerformed

    private void modCalcBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modCalcBtnActionPerformed
        // TODO add your handling code here:
        modOperations.modOperations();
    }//GEN-LAST:event_modCalcBtnActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        isbnInputField.setText("");
        creditCardNoInputField.setText("");
        outputField.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RunGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RunGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RunGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RunGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RunGUI().setVisible(true);
            }
        });
    }
    
    public void setup() {
        isbnVerification = new ISBNVerification();
        creditCardNoVerification = new CreditCardNoVerification();
        modOperations = new ModOperations();
    }
    
    private ISBNVerification isbnVerification;
    private CreditCardNoVerification creditCardNoVerification;
    private ModOperations modOperations;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField creditCardNoInputField;
    private javax.swing.JLabel creditCardNoInputLabel;
    private javax.swing.JLabel footnoteLabel;
    private javax.swing.JTextField isbnInputField;
    private javax.swing.JLabel isbnInputLabel;
    private javax.swing.JButton modCalcBtn;
    private javax.swing.JTextArea outputField;
    private javax.swing.JScrollPane outputScrollPane;
    private javax.swing.JButton verifyCreditCardNoButton;
    private javax.swing.JButton verifyISBNButton;
    // End of variables declaration//GEN-END:variables
}
